#!/usr/bin/env node
// Generates assets/header.svg — the ASCII figlet wordmark with a seeded
// noise-dissolve resolve. All animation is CSS steps() baked into the SVG,
// so it renders through GitHub's camo proxy with no JS and honors
// prefers-reduced-motion. Deterministic: same seed -> same file.
//
// Rerun only when the wordmark, tagline, or timing changes:
//   node scripts/generate-header.js

const { writeFileSync } = require("node:fs");
const { join } = require("node:path");

// ANSI Shadow figlet, "Maximus Beato" — keep in sync with the tagline below.
const ROWS = [
  "███╗   ███╗ █████╗ ██╗  ██╗██╗███╗   ███╗██╗   ██╗███████╗    ██████╗ ███████╗ █████╗ ████████╗ ██████╗ ",
  "████╗ ████║██╔══██╗╚██╗██╔╝██║████╗ ████║██║   ██║██╔════╝    ██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔═══██╗",
  "██╔████╔██║███████║ ╚███╔╝ ██║██╔████╔██║██║   ██║███████╗    ██████╔╝█████╗  ███████║   ██║   ██║   ██║",
  "██║╚██╔╝██║██╔══██║ ██╔██╗ ██║██║╚██╔╝██║██║   ██║╚════██║    ██╔══██╗██╔══╝  ██╔══██║   ██║   ██║   ██║",
  "██║ ╚═╝ ██║██║  ██║██╔╝ ██╗██║██║ ╚═╝ ██║╚██████╔╝███████║    ██████╔╝███████╗██║  ██║   ██║   ╚██████╔╝",
  "╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝    ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ",
];

const TAGLINE = "building tools for the agentic web — recense · tonos · jobfill";
const STATUS = "available for seed-stage roles ↗";

const SEED = 0x5eed;
const BAND = 5; // chars per resolve band — small enough to read as a wave, not chunks
const X = 42;
const Y0 = 102;
const LH = 16;

function mulberry32(a) {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(SEED);

// Silhouette-preserving noise: glyph cells become ░▒▓, spaces stay spaces,
// so the signal keeps its shape while it decrypts.
function noisify(s) {
  let out = "";
  for (const ch of s) {
    if (ch === " ") {
      out += " ";
    } else {
      const r = rand();
      out += r < 0.35 ? "░" : r < 0.75 ? "▒" : "▓";
    }
  }
  return out;
}

function bands(s) {
  const out = [];
  for (let i = 0; i < s.length; i += BAND) out.push(s.slice(i, i + BAND));
  return out;
}

// Per-band resolve delays: a diagonal wave — left→right sweep with a slight
// downward lag per row and just enough jitter to feel organic. Bands
// cross-fade (see CSS) so the front reads as smooth. Settles by ~1.85s.
const rowBands = ROWS.map((row, ri) => {
  const chunks = bands(row);
  return chunks.map((text, bi) => ({
    text,
    noise: noisify(text),
    delay: (0.25 + bi * 0.055 + ri * 0.045 + rand() * 0.06).toFixed(3),
  }));
});

const noiseRows = rowBands
  .map((chunks, ri) => {
    const tspans = chunks
      .map((b) => `<tspan style="animation-delay:${b.delay}s">${b.noise}</tspan>`)
      .join("");
    return `  <text class="n" xml:space="preserve" x="${X}" y="${Y0 + ri * LH}" font-size="13" fill="#5b6470">${tspans}</text>`;
  })
  .join("\n");

const finalRows = rowBands
  .map((chunks, ri) => {
    const tspans = chunks
      .map((b) => `<tspan style="animation-delay:${b.delay}s">${b.text}</tspan>`)
      .join("");
    return `  <text class="f" xml:space="preserve" x="${X}" y="${Y0 + ri * LH}" font-size="13" fill="#c9d1d9">${tspans}</text>`;
  })
  .join("\n");

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 280" width="900" height="280" font-family="ui-monospace, 'SF Mono', Menlo, Monaco, monospace">
  <!--
   Pattern: ascii-wordmark + sparse-corner-chrome, noise-dissolve resolve
   Source: Nozomio (nozomio.com) + Ghostty ASCII mark, corpus refs
   Generated by scripts/generate-header.js (seeded, deterministic) — edit that, not this.
  -->
  <style>
    /* fill-opacity, not opacity: Firefox doesn't apply opacity to tspans.
       Defaults are the resolved state, so if animations don't run at all
       the header degrades to the static wordmark, never stuck noise. */
    .n tspan { fill-opacity: 0; animation: off .22s ease-out both; }
    .f tspan { animation: on .22s ease-in both; }
    .n { animation: flick .22s steps(2, end) infinite; }
    .chrome { animation: chromeon .3s ease-out 1.72s both; }
    @keyframes off { from { fill-opacity: 1; } to { fill-opacity: 0; } }
    @keyframes on { from { fill-opacity: 0; } to { fill-opacity: 1; } }
    @keyframes flick { 50% { opacity: .72; } }
    @keyframes chromeon { from { opacity: 0; } to { opacity: 1; } }
    @media (prefers-reduced-motion: reduce) {
      .n, .n tspan, .f tspan, .chrome { animation: none; }
    }
  </style>
  <rect width="900" height="280" fill="#08080b"/>

  <!-- noise layer (resolves out band-by-band) -->
${noiseRows}

  <!-- resolved wordmark -->
${finalRows}

  <!-- corner chrome + taglines: appear once the signal locks -->
  <g class="chrome">
    <text x="40" y="34" font-size="11" letter-spacing="2" fill="#8b949e">◆ MAXIMUS BEATO</text>
    <text x="40" y="50" font-size="11" letter-spacing="2" fill="#4b5563">CTO · VERTIKALX</text>
    <text x="860" y="34" text-anchor="end" font-size="11" letter-spacing="2" fill="#4b5563">PURDUE CS ALUM</text>
    <text x="450" y="218" text-anchor="middle" font-size="12.5" letter-spacing="1" fill="#6b7280">${TAGLINE}</text>
    <text x="450" y="256" text-anchor="middle" font-size="12" letter-spacing="1" fill="#6b7280">${STATUS}</text>
  </g>
</svg>
`;

const out = join(__dirname, "..", "assets", "header.svg");
writeFileSync(out, svg);
console.log(`wrote ${out} (${svg.length} bytes, ${rowBands.flat().length} bands)`);
